# Generated by Django 4.0.5 on 2022-06-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callerIDapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spamnumbers',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='spam',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='callerIDapp.spamnumbers'),
        ),
        migrations.AddField(
            model_name='phonebook',
            name='spam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='callerIDapp.spamnumbers'),
        ),
    ]
