# Generated by Django 4.0.5 on 2022-06-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callerIDapp', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonebook',
            name='spam',
        ),
    ]
